config/routes.rb
Rails.application.routes.draw do
  resources :learns

end

app/models/learn.rb
class Learn < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/learns_controller.rb
class LearnsController < ApplicationController
  before_action :set_learn, only: [:show, :edit, :update, :destroy]

  # GET /learns
  # GET /learns.json
  def index
    @learns = Learn.all
  end

  # GET /learns/1
  # GET /learns/1.json
  def show
  end

  # GET /learns/new
  def new
    @learn = Learn.new
  end

  # GET /learns/1/edit
  def edit
  end

  # POST /learns
  # POST /learns.json
  def create
    @learn = Learn.new(learn_params)

    respond_to do |format|
      if @learn.save
        format.html { redirect_to @learn, notice: 'Learn was successfully created.' }
        format.json { render :show, status: :created, location: @learn }
      else
        format.html { render :new }
        format.json { render json: @learn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /learns/1
  # PATCH/PUT /learns/1.json
  def update
    respond_to do |format|
      if @learn.update(learn_params)
        format.html { redirect_to @learn, notice: 'Learn was successfully updated.' }
        format.json { render :show, status: :ok, location: @learn }
      else
        format.html { render :edit }
        format.json { render json: @learn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /learns/1
  # DELETE /learns/1.json
  def destroy
    @learn.destroy
    respond_to do |format|
      format.html { redirect_to learns_url, notice: 'Learn was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_learn
      @learn = Learn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def learn_params
      params.require(:learn).permit(:topic, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/learns_helper.rb
module LearnsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LearnRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/learns/_form.html.erb
<%= form_for(@learn) do |f| %>
  <% if @learn.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@learn.errors.count, "error") %> prohibited this learn from being saved:</h2>

      <ul>
      <% @learn.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :topic %><br>
    <%= f.text_field :topic %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/learns/edit.html.erb
<h1>Editing Learn</h1>

<%= render 'form' %>

<%= link_to 'Show', @learn %> |
<%= link_to 'Back', learns_path %>

app/views/learns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Learns</h1>

<table>
  <thead>
    <tr>
      <th>Topic</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @learns.each do |learn| %>
      <tr>
        <td><%= learn.topic %></td>
        <td><%= learn.description %></td>
        <td><%= link_to 'Show', learn %></td>
        <td><%= link_to 'Edit', edit_learn_path(learn) %></td>
        <td><%= link_to 'Destroy', learn, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Learn', new_learn_path %>

app/views/learns/new.html.erb
<h1>New Learn</h1>

<%= render 'form' %>

<%= link_to 'Back', learns_path %>

app/views/learns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Topic:</strong>
  <%= @learn.topic %>
</p>

<p>
  <strong>Description:</strong>
  <%= @learn.description %>
</p>

<%= link_to 'Edit', edit_learn_path(@learn) %> |
<%= link_to 'Back', learns_path %>